# Generated by Django 6.0.7 on 2026-07-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='name',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='designationcategory',
            old_name='name',
            new_name='designation_category',
        ),
    ]
