# Generated by Django 6.0.7 on 2026-07-31 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowance',
            options={'ordering': ['allowance'], 'verbose_name': 'Allowance', 'verbose_name_plural': 'Allowances'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='deduction',
            options={'ordering': ['deduction'], 'verbose_name': 'Deduction', 'verbose_name_plural': 'Deductions'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['designation'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender'], 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='salarymode',
            options={'ordering': ['salary_mode'], 'verbose_name': 'Salary Mode', 'verbose_name_plural': 'Salary Modes'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['shift'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state'], 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.RemoveField(
            model_name='designation',
            name='category',
        ),
        migrations.AddField(
            model_name='designation',
            name='designation_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='designations', to='master.designationcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allowance',
            name='allowance',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='master.state'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='deduction',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='states', to='master.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'city'), name='unique_state_city'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'state'), name='unique_country_state'),
        ),
    ]
