# Generated by Django 6.0.7 on 2026-07-31 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='salary.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'allowance')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='salary.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'deduction')},
            },
        ),
    ]
