# Generated by Django 6.0.7 on 2026-07-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeallowance',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.allowance'),
        ),
        migrations.AlterField(
            model_name='employeededuction',
            name='deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.deduction'),
        ),
        migrations.DeleteModel(
            name='Allowance',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
