# Generated by Django 6.0.7 on 2026-07-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.shift'),
        ),
    ]
