# Generated by Django 6.0.7 on 2026-07-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('holiday', '0002_alter_holiday_shift'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.shift'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.shift'),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
